DESCRIPTIONS: dict[str, str] = {
    # Scale Categories
    "major_scales": "The foundation of Western music harmony, following the W-W-H-W-W-W-H pattern.",
    "natural_minor_scales": "Also known as the Aeolian mode, constructed using the W-H-W-W-H-W-W pattern.",
    "harmonic_minor_scales": "A natural minor scale with a raised 7th degree, creating a leading tone and an exotic augmented second interval.",
    "melodic_minor_scales": "Raises both the 6th and 7th degrees ascending, and reverts to natural minor descending to optimize smooth voice leading.",
    "chromatic_scales": "A scale consisting of all twelve semitones of the octave, moving in half steps.",
    "major_pentatonic_scales": "A five-note scale omitting the 4th and 7th degrees, popular in folk and rock music.",
    "minor_pentatonic_scales": "A five-note minor scale omitting the 2nd and 6th degrees, key to blues and rock solos.",
    "blues_scales": "A hexatonic scale adding the flatted 5th ('blue note') to the minor pentatonic scale.",
    "whole_tone_scales": "A six-note scale built entirely of whole steps, creating an atmospheric, dreamlike sound.",
    "diminished_scales": "An eight-note scale built on alternating half and whole steps, used in jazz contexts.",
    "bebop_scales": "An eight-note dominant scale incorporating an extra chromatic passing tone between the 7th and root.",

    # Modes Categories
    "ionian_mode": "The natural major scale, serving as the base model for relative mode intervals.",
    "dorian_mode": "A minor mode characterized by a major 6th, conveying a bright minor or jazzy sound.",
    "phrygian_mode": "A minor mode characterized by a flat 2nd, conveying a Spanish or heavy sound.",
    "lydian_mode": "A major mode characterized by a sharp 4th, conveying an ethereal, spacey sound.",
    "mixolydian_mode": "A major mode characterized by a flat 7th, common in blues, rock, and Celtic music.",
    "aeolian_mode": "The natural minor scale, conveying a sad or epic classical mood.",
    "locrian_mode": "A diminished mode characterized by a flat 2nd and flat 5th, conveying a dark, unstable sound.",

    # Arpeggio Categories
    "major_arpeggios": "Notes of a major triad played sequentially.",
    "minor_arpeggios": "Notes of a minor triad played sequentially.",
    "diminished_arpeggios": "Notes of a diminished triad played sequentially.",
    "augmented_arpeggios": "Notes of an augmented triad played sequentially.",
    "dominant_seventh_arpeggios": "Notes of a dominant 7th chord played sequentially.",
    "major_seventh_arpeggios": "Notes of a major 7th chord played sequentially.",
    "minor_seventh_arpeggios": "Notes of a minor 7th chord played sequentially.",

    # Chord Categories
    "major_chords": "Three-note major chord containing Root, Major 3rd, and Perfect 5th.",
    "minor_chords": "Three-note minor chord containing Root, minor 3rd, and Perfect 5th.",
    "diminished_chords": "Three-note diminished chord containing Root, minor 3rd, and diminished 5th.",
    "augmented_chords": "Three-note augmented chord containing Root, Major 3rd, and augmented 5th.",
    "suspended_chords": "Chord replacing the 3rd with a Perfect 4th, creating an unresolved harmonic tension.",
    "dominant_seventh_chords": "Four-note chord containing Root, Major 3rd, Perfect 5th, and minor 7th.",
    "major_seventh_chords": "Four-note chord containing Root, Major 3rd, Perfect 5th, and Major 7th.",
    "minor_seventh_chords": "Four-note chord containing Root, minor 3rd, Perfect 5th, and minor 7th.",
    "half_diminished_chords": "Minor 7th flat 5 chord (m7b5) containing minor 3rd, diminished 5th, and minor 7th.",
    "fully_diminished_chords": "Diminished 7th chord containing minor 3rd, diminished 5th, and diminished 7th.",
    "sixth_chords": "Major triad with an added major 6th degree.",
    "ninth_chords": "Five-note dominant chord with an added major 9th degree.",
    "eleventh_chords": "Six-note dominant chord with an added major 11th degree (often omitting the 3rd).",
    "thirteenth_chords": "Seven-note dominant chord with an added major 13th degree.",
    "altered_chords": "Dominant seventh chord with alterations to the 5th and/or 9th degrees.",

    # Diatonic Interval Categories
    "interval_unison": "Zero semitone distance; identical pitches played together.",
    "interval_minor_second": "One semitone distance; highly dissonant and tense.",
    "interval_major_second": "Two semitones distance; step-wise melodic motion.",
    "interval_minor_third": "Three semitones distance; defines a minor key signature flavor.",
    "interval_major_third": "Four semitones distance; defines a major key signature flavor.",
    "interval_perfect_fourth": "Five semitones distance; stable and harmonically hollow.",
    "interval_tritone": "Six semitones distance; highly unstable augmented 4th/diminished 5th.",
    "interval_perfect_fifth": "Seven semitones distance; extremely stable consonant interval.",
    "interval_minor_sixth": "Eight semitones distance; rich, poignant classical intervals.",
    "interval_major_sixth": "Nine semitones distance; warm, bright interval flavor.",
    "interval_minor_seventh": "Ten semitones distance; key constituent of dominant seventh sounds.",
    "interval_major_seventh": "Eleven semitones distance; sharp dissonant leading tone pull.",
    "interval_octave": "Twelve semitones distance; identical letter name pitch at double frequency."
}

KEY_DESCRIPTIONS: dict[str, dict[str, str]] = {
    "major_scale": {
        "C":  "No sharps or flats; reference key for Western theory.",
        "C#": "Seven sharps; spelling includes E♯ and B♯.",
        "Db": "Enharmonic equivalent to C# Major. Spelled with five flats.",
        "D":  "Two sharps (F♯, C♯); bright and resonant scale.",
        "D#": "Nine sharps; often represented as E♭ major.",
        "Eb": "Enharmonic equivalent to D# Major. Spelled with three flats.",
        "E":  "Four sharps (F♯, C♯, G♯, D♯); bright, resonant key.",
        "F":  "One flat (B♭); warm, rich tone.",
        "F#": "Six sharps (F♯, C♯, G♯, D♯, A♯, E♯); popular keyboard key.",
        "Gb": "Enharmonic equivalent to F# Major. Spelled with six flats.",
        "G":  "One sharp (F♯); common for guitar and violin.",
        "G#": "Eight sharps; often represented as A♭ major.",
        "Ab": "Enharmonic equivalent to G# Major. Spelled with four flats.",
        "A":  "Three sharps (F♯, C♯, G♯); cheerful and warm key.",
        "A#": "Ten sharps; often represented as B♭ major.",
        "Bb": "Enharmonic equivalent to A# Major. Spelled with two flats.",
        "B":  "Five sharps (F♯, C♯, G♯, D♯, A♯); resonant key for strings and piano."
    },
    "natural_minor_scale": {
        "C":  "Relative minor of Eb major; contains three flats (B♭, E♭, A♭).",
        "C#": "Relative minor of E major; contains four sharps (F♯, C♯, G♯, D♯).",
        "Db": "Enharmonic equivalent to C# Natural Minor. Spelled with flats.",
        "D":  "Relative minor of F major; contains one flat (B♭).",
        "D#": "Relative minor of F# major; contains six sharps (F♯, C♯, G♯, D♯, A♯, E♯).",
        "Eb": "Enharmonic equivalent to D# Natural Minor. Spelled with flats.",
        "E":  "Relative minor of G major; contains one sharp (F♯).",
        "F":  "Relative minor of Ab major; contains four flats (B♭, E♭, A♭, D♭).",
        "F#": "Relative minor of A major; contains three sharps (F♯, C♯, G♯).",
        "Gb": "Enharmonic equivalent to F# Natural Minor. Spelled with flats.",
        "G":  "Relative minor of Bb major; contains two flats (B♭, E♭).",
        "G#": "Relative minor of B major; contains five sharps (F♯, C♯, G♯, D♯, A♯).",
        "Ab": "Enharmonic equivalent to G# Natural Minor. Spelled with flats.",
        "A":  "Relative minor of C major; contains no sharps or flats.",
        "A#": "Relative minor of C# major; contains seven sharps.",
        "Bb": "Enharmonic equivalent to A# Natural Minor. Spelled with flats.",
        "B":  "Relative minor of D major; contains two sharps (F♯, C♯)."
    },
    "harmonic_minor_scale": {
        "C":  "Raised 7th degree (B) pulls back to C.",
        "C#": "Raised 7th degree (B♯) pulls back to C♯.",
        "Db": "Enharmonic equivalent to C# Harmonic Minor. Spelled with flats.",
        "D":  "Raised 7th degree (C♯) creates a strong pull back to D.",
        "D#": "Raised 7th degree (C𝄪) creates a strong pull back to D♯.",
        "Eb": "Enharmonic equivalent to D# Harmonic Minor. Spelled with flats.",
        "E":  "Raised 7th degree (D♯) creates a strong pull back to E.",
        "F":  "Raised 7th degree (E) creates a strong pull back to F.",
        "F#": "Raised 7th degree (E♯) creates a strong pull back to F♯.",
        "Gb": "Enharmonic equivalent to F# Harmonic Minor. Spelled with flats.",
        "G":  "Raised 7th degree (F♯) creates a strong pull back to G.",
        "G#": "Raised 7th degree (F𝄪) creates a strong pull back to G♯.",
        "Ab": "Enharmonic equivalent to G# Harmonic Minor. Spelled with flats.",
        "A":  "G♯ leads strongly back to the tonic A; distinctive minor key sound.",
        "A#": "Raised 7th degree (G𝄪) pulls back to A♯.",
        "Bb": "Enharmonic equivalent to A# Harmonic Minor. Spelled with flats.",
        "B":  "Raised 7th degree (A♯) pulls back to B."
    },
    "melodic_minor_scale": {
        "C":  "Raised 6th (A) and raised 7th (B) ascending, natural minor descending.",
        "C#": "Raised 6th (A♯) and raised 7th (B♯) ascending, natural minor descending.",
        "Db": "Enharmonic equivalent to C# Melodic Minor. Spelled with flats.",
        "D":  "Raised 6th (B) and raised 7th (C♯) ascending, natural minor descending.",
        "D#": "Raised 6th (B♯) and raised 7th (C𝄪) ascending, natural minor descending.",
        "Eb": "Enharmonic equivalent to D# Melodic Minor. Spelled with flats.",
        "E":  "Raised 6th (C♯) and raised 7th (D♯) ascending, natural minor descending.",
        "F":  "Raised 6th (D) and raised 7th (E) ascending, natural minor descending.",
        "F#": "Raised 6th (D♯) and raised 7th (E♯) ascending, natural minor descending.",
        "Gb": "Enharmonic equivalent to F# Melodic Minor. Spelled with flats.",
        "G":  "Raised 6th (E) and raised 7th (F♯) ascending, natural minor descending.",
        "G#": "Raised 6th (E♯) and raised 7th (F𝄪) ascending, natural minor descending.",
        "Ab": "Enharmonic equivalent to G# Melodic Minor. Spelled with flats.",
        "A":  "F♯ and G♯ are raised when ascending for smooth melodic flow, natural minor descending.",
        "A#": "F𝄪 and G𝄪 are raised when ascending, natural minor descending.",
        "Bb": "Enharmonic equivalent to A# Melodic Minor. Spelled with flats.",
        "B":  "G♯ and A♯ are raised when ascending, natural minor descending."
    }
}
