export interface ScaleInfo {
  name: string;
  keySignature: string;
  notes: string[];
  relativeMinor: string;
  formula: string;
  degrees: string[];
  degreeNames: string[];
  rightHandFingering: string;
  leftHandFingering: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  relatedChords: string[];
  relatedArpeggios: string[];
  playNotes: string[]; // notes with octave indicators for synthesis (C4, D4, etc)
  enharmonicEquivalent?: string;
}

export const SCALES_REGISTRY: Record<string, ScaleInfo> = {
  // --- MAJOR SCALES (12 Keys + 5 Enharmonics) ---
  'C Major': {
    name: 'C Major',
    keySignature: '0 Sharps/Flats',
    notes: ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
    relativeMinor: 'A Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Beginner',
    relatedChords: ['C Major Triad (I)', 'F Major Triad (IV)', 'G Dominant 7th (V7)'],
    relatedArpeggios: ['C Major Arpeggio', 'A Minor Arpeggio'],
    playNotes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5'],
  },
  'C# Major': {
    name: 'C# Major',
    keySignature: '7 Sharps (F♯, C♯, G♯, D♯, A♯, E♯, B♯)',
    notes: ['C#', 'D#', 'F', 'F#', 'G#', 'A#', 'C'],
    relativeMinor: 'A# Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['C# Major Triad (I)', 'F# Major Triad (IV)', 'G# Dominant 7th (V7)'],
    relatedArpeggios: ['C# Major Arpeggio', 'A# Minor Arpeggio'],
    playNotes: ['C#4', 'D#4', 'F4', 'F#4', 'G#4', 'A#4', 'C5', 'C#5'],
    enharmonicEquivalent: 'Db Major',
  },
  'Db Major': {
    name: 'Db Major',
    keySignature: '5 Flats (B♭, E♭, A♭, D♭, G♭)',
    notes: ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C'],
    relativeMinor: 'Bb Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Db Major Triad (I)', 'Gb Major Triad (IV)', 'Ab Dominant 7th (V7)'],
    relatedArpeggios: ['Db Major Arpeggio', 'Bb Minor Arpeggio'],
    playNotes: ['Db4', 'Eb4', 'F4', 'Gb4', 'Ab4', 'Bb4', 'C5', 'Db5'],
    enharmonicEquivalent: 'C# Major',
  },
  'D Major': {
    name: 'D Major',
    keySignature: '2 Sharps (F♯, C♯)',
    notes: ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
    relativeMinor: 'B Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['D Major Triad (I)', 'G Major Triad (IV)', 'A Dominant 7th (V7)'],
    relatedArpeggios: ['D Major Arpeggio', 'B Minor Arpeggio'],
    playNotes: ['D4', 'E4', 'F#4', 'G4', 'A4', 'B4', 'C#5', 'D5'],
  },
  'D# Major': {
    name: 'D# Major',
    keySignature: '9 Sharps (F♯, C♯, G♯, D♯, A♯, E♯, B♯, F𝄪, C𝄪)',
    notes: ['D#', 'F', 'G', 'G#', 'A#', 'C', 'D'],
    relativeMinor: 'C Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-1-2-3-4-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Eb Major Triad (I)', 'Ab Major Triad (IV)', 'Bb Dominant 7th (V7)'],
    relatedArpeggios: ['Eb Major Arpeggio', 'C Minor Arpeggio'],
    playNotes: ['D#4', 'F4', 'G4', 'G#4', 'A#4', 'C5', 'D5', 'D#5'],
    enharmonicEquivalent: 'Eb Major',
  },
  'Eb Major': {
    name: 'Eb Major',
    keySignature: '3 Flats (B♭, E♭, A♭)',
    notes: ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D'],
    relativeMinor: 'C Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-1-2-3-4-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Intermediate',
    relatedChords: ['Eb Major Triad (I)', 'Ab Major Triad (IV)', 'Bb Dominant 7th (V7)'],
    relatedArpeggios: ['Eb Major Arpeggio', 'C Minor Arpeggio'],
    playNotes: ['Eb4', 'F4', 'G4', 'Ab4', 'Bb4', 'C5', 'D5', 'Eb5'],
    enharmonicEquivalent: 'D# Major',
  },
  'E Major': {
    name: 'E Major',
    keySignature: '4 Sharps (F♯, C♯, G♯, D♯)',
    notes: ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
    relativeMinor: 'C# Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['E Major Triad (I)', 'A Major Triad (IV)', 'B Dominant 7th (V7)'],
    relatedArpeggios: ['E Major Arpeggio', 'C# Minor Arpeggio'],
    playNotes: ['E4', 'F#4', 'G#4', 'A4', 'B4', 'C#5', 'D#5', 'E5'],
  },
  'F Major': {
    name: 'F Major',
    keySignature: '1 Flat (B♭)',
    notes: ['F', 'G', 'A', 'A#', 'C', 'D', 'E'],
    relativeMinor: 'D Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-4-1-2-3-4',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Beginner',
    relatedChords: ['F Major Triad (I)', 'Bb Major Triad (IV)', 'C Dominant 7th (V7)'],
    relatedArpeggios: ['F Major Arpeggio', 'D Minor Arpeggio'],
    playNotes: ['F4', 'G4', 'A4', 'Bb4', 'C5', 'D5', 'E5', 'F5'],
  },
  'F# Major': {
    name: 'F# Major',
    keySignature: '6 Sharps (F♯, C♯, G♯, D♯, A♯, E♯)',
    notes: ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'F'],
    relativeMinor: 'D# Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-4-1-2-3-4-1',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Advanced',
    relatedChords: ['F# Major Triad (I)', 'B Major Triad (IV)', 'C# Dominant 7th (V7)'],
    relatedArpeggios: ['F# Major Arpeggio', 'D# Minor Arpeggio'],
    playNotes: ['F#4', 'G#4', 'A#4', 'B4', 'C#5', 'D#5', 'F5', 'F#5'],
    enharmonicEquivalent: 'Gb Major',
  },
  'Gb Major': {
    name: 'Gb Major',
    keySignature: '6 Flats (B♭, E♭, A♭, D♭, G♭, C♭)',
    notes: ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F'],
    relativeMinor: 'Eb Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-4-1-2-3-4-1',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Advanced',
    relatedChords: ['Gb Major Triad (I)', 'Cb Major Triad (IV)', 'Db Dominant 7th (V7)'],
    relatedArpeggios: ['Gb Major Arpeggio', 'Eb Minor Arpeggio'],
    playNotes: ['Gb4', 'Ab4', 'Bb4', 'Cb5', 'Db5', 'Eb5', 'F5', 'Gb5'],
    enharmonicEquivalent: 'F# Major',
  },
  'G Major': {
    name: 'G Major',
    keySignature: '1 Sharp (F♯)',
    notes: ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
    relativeMinor: 'E Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Beginner',
    relatedChords: ['G Major Triad (I)', 'C Major Triad (IV)', 'D Dominant 7th (V7)'],
    relatedArpeggios: ['G Major Arpeggio', 'E Minor Arpeggio'],
    playNotes: ['G4', 'A4', 'B4', 'C5', 'D5', 'E5', 'F#5', 'G5'],
  },
  'G# Major': {
    name: 'G# Major',
    keySignature: '8 Sharps (F♯, C♯, G♯, D♯, A♯, E♯, B♯, F𝄪)',
    notes: ['G#', 'A#', 'C', 'C#', 'D#', 'F', 'G'],
    relativeMinor: 'F Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Ab Major Triad (I)', 'Db Major Triad (IV)', 'Eb Dominant 7th (V7)'],
    relatedArpeggios: ['Ab Major Arpeggio', 'F Minor Arpeggio'],
    playNotes: ['G#4', 'A#4', 'C5', 'C#5', 'D#5', 'F5', 'G5', 'G#5'],
    enharmonicEquivalent: 'Ab Major',
  },
  'Ab Major': {
    name: 'Ab Major',
    keySignature: '4 Flats (B♭, E♭, A♭, D♭)',
    notes: ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G'],
    relativeMinor: 'F Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Ab Major Triad (I)', 'Db Major Triad (IV)', 'Eb Dominant 7th (V7)'],
    relatedArpeggios: ['Ab Major Arpeggio', 'F Minor Arpeggio'],
    playNotes: ['Ab4', 'Bb4', 'C5', 'Db5', 'Eb5', 'F5', 'G5', 'Ab5'],
    enharmonicEquivalent: 'G# Major',
  },
  'A Major': {
    name: 'A Major',
    keySignature: '3 Sharps (F♯, C♯, G♯)',
    notes: ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
    relativeMinor: 'F# Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['A Major Triad (I)', 'D Major Triad (IV)', 'E Dominant 7th (V7)'],
    relatedArpeggios: ['A Major Arpeggio', 'F# Minor Arpeggio'],
    playNotes: ['A4', 'B4', 'C#5', 'D5', 'E5', 'F#5', 'G#5', 'A5'],
  },
  'A# Major': {
    name: 'A# Major',
    keySignature: '10 Sharps (F♯, C♯, G♯, D♯, A♯, E♯, B♯, F𝄪, C𝄪, G𝄪)',
    notes: ['A#', 'C', 'D', 'D#', 'F', 'G', 'A'],
    relativeMinor: 'G Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Bb Major Triad (I)', 'Eb Major Triad (IV)', 'F Dominant 7th (V7)'],
    relatedArpeggios: ['Bb Major Arpeggio', 'G Minor Arpeggio'],
    playNotes: ['A#4', 'C5', 'D5', 'D#5', 'F5', 'G5', 'A5', 'A#5'],
    enharmonicEquivalent: 'Bb Major',
  },
  'Bb Major': {
    name: 'Bb Major',
    keySignature: '2 Flats (B♭, E♭)',
    notes: ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'A'],
    relativeMinor: 'G Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Intermediate',
    relatedChords: ['Bb Major Triad (I)', 'Eb Major Triad (IV)', 'F Dominant 7th (V7)'],
    relatedArpeggios: ['Bb Major Arpeggio', 'G Minor Arpeggio'],
    playNotes: ['Bb4', 'C5', 'D5', 'Eb5', 'F5', 'G5', 'A5', 'Bb5'],
    enharmonicEquivalent: 'A# Major',
  },
  'B Major': {
    name: 'B Major',
    keySignature: '5 Sharps (F♯, C♯, G♯, D♯, A♯)',
    notes: ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
    relativeMinor: 'G# Natural Minor',
    formula: 'W-W-H-W-W-W-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Intermediate',
    relatedChords: ['B Major Triad (I)', 'E Major Triad (IV)', 'F# Dominant 7th (V7)'],
    relatedArpeggios: ['B Major Arpeggio', 'G# Minor Arpeggio'],
    playNotes: ['B4', 'C#5', 'D#5', 'E5', 'F#5', 'G#5', 'A#5', 'B5'],
  },

  // --- NATURAL MINOR SCALES (12 Keys + 5 Enharmonics) ---
  'C Natural Minor': {
    name: 'C Natural Minor',
    keySignature: '3 Flats (B♭, E♭, A♭)',
    notes: ['C', 'D', 'D#', 'F', 'G', 'G#', 'A#'],
    relativeMinor: 'Eb Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Beginner',
    relatedChords: ['C Minor Triad (i)', 'F Minor Triad (iv)', 'G Minor Triad (v)'],
    relatedArpeggios: ['C Minor Arpeggio', 'Eb Major Arpeggio'],
    playNotes: ['C4', 'D4', 'Eb4', 'F4', 'G4', 'Ab4', 'Bb4', 'C5'],
  },
  'C# Natural Minor': {
    name: 'C# Natural Minor',
    keySignature: '4 Sharps (F♯, C♯, G♯, D♯)',
    notes: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
    relativeMinor: 'E Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['C# Minor Triad (i)', 'F# Minor Triad (iv)', 'G# Minor Triad (v)'],
    relatedArpeggios: ['C# Minor Arpeggio', 'E Major Arpeggio'],
    playNotes: ['C#4', 'D#4', 'E4', 'F#4', 'G#4', 'A4', 'B4', 'C#5'],
    enharmonicEquivalent: 'Db Natural Minor',
  },
  'Db Natural Minor': {
    name: 'Db Natural Minor',
    keySignature: '8 Flats (or 4 Sharps C#)',
    notes: ['Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'B'],
    relativeMinor: 'E Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['Db Minor Triad (i)', 'Gb Minor Triad (iv)', 'Ab Minor Triad (v)'],
    relatedArpeggios: ['Db Minor Arpeggio', 'E Major Arpeggio'],
    playNotes: ['Db4', 'Eb4', 'E4', 'Gb4', 'Ab4', 'A4', 'B4', 'Db5'],
    enharmonicEquivalent: 'C# Natural Minor',
  },
  'D Natural Minor': {
    name: 'D Natural Minor',
    keySignature: '1 Flat (B♭)',
    notes: ['D', 'E', 'F', 'G', 'A', 'A#', 'C'],
    relativeMinor: 'F Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['D Minor Triad (i)', 'G Minor Triad (iv)', 'A Minor Triad (v)'],
    relatedArpeggios: ['D Minor Arpeggio', 'F Major Arpeggio'],
    playNotes: ['D4', 'E4', 'F4', 'G4', 'A4', 'Bb4', 'C5', 'D5'],
  },
  'D# Natural Minor': {
    name: 'D# Natural Minor',
    keySignature: '6 Sharps (F♯, C♯, G♯, D♯, A♯, E♯)',
    notes: ['D#', 'F', 'F#', 'G#', 'A#', 'B', 'C#'],
    relativeMinor: 'F# Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['D# Minor Triad (i)', 'G# Minor Triad (iv)', 'A# Minor Triad (v)'],
    relatedArpeggios: ['D# Minor Arpeggio', 'F# Major Arpeggio'],
    playNotes: ['D#4', 'F4', 'F#4', 'G#4', 'A#4', 'B4', 'C#5', 'D#5'],
    enharmonicEquivalent: 'Eb Natural Minor',
  },
  'Eb Natural Minor': {
    name: 'Eb Natural Minor',
    keySignature: '6 Flats (B♭, E♭, A♭, D♭, G♭, C♭)',
    notes: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'B', 'Db'],
    relativeMinor: 'Gb Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Eb Minor Triad (i)', 'Ab Minor Triad (iv)', 'Bb Minor Triad (v)'],
    relatedArpeggios: ['Eb Minor Arpeggio', 'Gb Major Arpeggio'],
    playNotes: ['Eb4', 'F4', 'Gb4', 'Ab4', 'Bb4', 'B4', 'Db5', 'Eb5'],
    enharmonicEquivalent: 'D# Natural Minor',
  },
  'E Natural Minor': {
    name: 'E Natural Minor',
    keySignature: '1 Sharp (F♯)',
    notes: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
    relativeMinor: 'G Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Beginner',
    relatedChords: ['E Minor Triad (i)', 'A Minor Triad (iv)', 'B Minor Triad (v)'],
    relatedArpeggios: ['E Minor Arpeggio', 'G Major Arpeggio'],
    playNotes: ['E4', 'F#4', 'G4', 'A4', 'B4', 'C5', 'D5', 'E5'],
  },
  'F Natural Minor': {
    name: 'F Natural Minor',
    keySignature: '4 Flats (B♭, E♭, A♭, D♭)',
    notes: ['F', 'G', 'G#', 'A#', 'C', 'C#', 'D#'],
    relativeMinor: 'Ab Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-4-1-2-3-4',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['F Minor Triad (i)', 'Bb Minor Triad (iv)', 'C Minor Triad (v)'],
    relatedArpeggios: ['F Minor Arpeggio', 'Ab Major Arpeggio'],
    playNotes: ['F4', 'G4', 'Ab4', 'Bb4', 'C5', 'D5', 'Eb5', 'F5'],
  },
  'F# Natural Minor': {
    name: 'F# Natural Minor',
    keySignature: '3 Sharps (F♯, C♯, G♯)',
    notes: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
    relativeMinor: 'A Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Intermediate',
    relatedChords: ['F# Minor Triad (i)', 'B Minor Triad (iv)', 'C# Minor Triad (v)'],
    relatedArpeggios: ['F# Minor Arpeggio', 'A Major Arpeggio'],
    playNotes: ['F#4', 'G#4', 'A4', 'B4', 'C#5', 'D5', 'E5', 'F#5'],
    enharmonicEquivalent: 'Gb Natural Minor',
  },
  'Gb Natural Minor': {
    name: 'Gb Natural Minor',
    keySignature: '9 Flats (or 3 Sharps F#)',
    notes: ['Gb', 'Ab', 'A', 'B', 'Db', 'D', 'E'],
    relativeMinor: 'A Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Intermediate',
    relatedChords: ['Gb Minor Triad (i)', 'Cb Minor Triad (iv)', 'Db Minor Triad (v)'],
    relatedArpeggios: ['Gb Minor Arpeggio', 'A Major Arpeggio'],
    playNotes: ['Gb4', 'Ab4', 'A4', 'B4', 'Db5', 'D5', 'E5', 'Gb5'],
    enharmonicEquivalent: 'F# Natural Minor',
  },
  'G Natural Minor': {
    name: 'G Natural Minor',
    keySignature: '2 Flats (B♭, E♭)',
    notes: ['G', 'A', 'A#', 'C', 'D', 'D#', 'F'],
    relativeMinor: 'Bb Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['G Minor Triad (i)', 'C Minor Triad (iv)', 'D Minor Triad (v)'],
    relatedArpeggios: ['G Minor Arpeggio', 'Bb Major Arpeggio'],
    playNotes: ['G4', 'A4', 'Bb4', 'C5', 'D5', 'Eb5', 'F5', 'G5'],
  },
  'G# Natural Minor': {
    name: 'G# Natural Minor',
    keySignature: '5 Sharps (F♯, C♯, G♯, D♯, A♯)',
    notes: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
    relativeMinor: 'B Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['G# Minor Triad (i)', 'C# Minor Triad (iv)', 'D# Minor Triad (v)'],
    relatedArpeggios: ['G# Minor Arpeggio', 'B Major Arpeggio'],
    playNotes: ['G#4', 'A#4', 'B4', 'C#5', 'D#5', 'E5', 'F#5', 'G#5'],
    enharmonicEquivalent: 'Ab Natural Minor',
  },
  'Ab Natural Minor': {
    name: 'Ab Natural Minor',
    keySignature: '7 Flats (B♭, E♭, A♭, D♭, G♭, C♭, F♭)',
    notes: ['Ab', 'Bb', 'B', 'Db', 'Eb', 'E', 'Gb'],
    relativeMinor: 'B Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Ab Minor Triad (i)', 'Db Minor Triad (iv)', 'Eb Minor Triad (v)'],
    relatedArpeggios: ['Ab Minor Arpeggio', 'B Major Arpeggio'],
    playNotes: ['Ab4', 'Bb4', 'B4', 'Db5', 'Eb5', 'E5', 'Gb5', 'Ab5'],
    enharmonicEquivalent: 'G# Natural Minor',
  },
  'A Natural Minor': {
    name: 'A Natural Minor',
    keySignature: '0 Sharps/Flats',
    notes: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    relativeMinor: 'C Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Beginner',
    relatedChords: ['A Minor Triad (i)', 'D Minor Triad (iv)', 'E Minor Triad (v)'],
    relatedArpeggios: ['A Minor Arpeggio', 'C Major Arpeggio'],
    playNotes: ['A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G5', 'A5'],
  },
  'A# Natural Minor': {
    name: 'A# Natural Minor',
    keySignature: '7 Sharps (F♯, C♯, G♯, D♯, A♯, E♯, B♯)',
    notes: ['A#', 'C', 'C#', 'D#', 'F', 'F#', 'G#'],
    relativeMinor: 'C# Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['A# Minor Triad (i)', 'D# Minor Triad (iv)', 'E# Minor Triad (v)'],
    relatedArpeggios: ['A# Minor Arpeggio', 'C# Major Arpeggio'],
    playNotes: ['A#4', 'C5', 'C#5', 'D#5', 'F5', 'F#5', 'G#5', 'A#5'],
    enharmonicEquivalent: 'Bb Natural Minor',
  },
  'Bb Natural Minor': {
    name: 'Bb Natural Minor',
    keySignature: '5 Flats (B♭, E♭, A♭, D♭, G♭)',
    notes: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab'],
    relativeMinor: 'Db Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Bb Minor Triad (i)', 'Eb Minor Triad (iv)', 'F Minor Triad (v)'],
    relatedArpeggios: ['Bb Minor Arpeggio', 'Db Major Arpeggio'],
    playNotes: ['Bb4', 'C5', 'Db5', 'Eb5', 'F5', 'Gb5', 'Ab5', 'Bb5'],
    enharmonicEquivalent: 'A# Natural Minor',
  },
  'B Natural Minor': {
    name: 'B Natural Minor',
    keySignature: '2 Sharps (F♯, C♯)',
    notes: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
    relativeMinor: 'D Major (Relative Major)',
    formula: 'W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Subtonic'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Intermediate',
    relatedChords: ['B Minor Triad (i)', 'E Minor Triad (iv)', 'F# Minor Triad (v)'],
    relatedArpeggios: ['B Minor Arpeggio', 'D Major Arpeggio'],
    playNotes: ['B4', 'C#5', 'D5', 'E5', 'F#5', 'G5', 'A5', 'B5'],
  },

  // --- HARMONIC MINOR SCALES (12 Keys + 5 Enharmonics) ---
  'C Harmonic Minor': {
    name: 'C Harmonic Minor',
    keySignature: '3 Flats (B♮ raised)',
    notes: ['C', 'D', 'D#', 'F', 'G', 'G#', 'B'],
    relativeMinor: 'Eb Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['C Minor Triad (i)', 'F Minor Triad (iv)', 'G Major Triad (V)'],
    relatedArpeggios: ['C Minor Arpeggio', 'Eb Augmented Arpeggio'],
    playNotes: ['C4', 'D4', 'Eb4', 'F4', 'G4', 'Ab4', 'B4', 'C5'],
  },
  'C# Harmonic Minor': {
    name: 'C# Harmonic Minor',
    keySignature: '4 Sharps (B♯ raised)',
    notes: ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'C'],
    relativeMinor: 'E Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['C# Minor Triad (i)', 'F# Minor Triad (iv)', 'G# Major Triad (V)'],
    relatedArpeggios: ['C# Minor Arpeggio', 'E Augmented Arpeggio'],
    playNotes: ['C#4', 'D#4', 'E4', 'F#4', 'G#4', 'A4', 'C5', 'C#5'],
    enharmonicEquivalent: 'Db Harmonic Minor',
  },
  'Db Harmonic Minor': {
    name: 'Db Harmonic Minor',
    keySignature: '8 Flats (C♮ raised)',
    notes: ['Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'C'],
    relativeMinor: 'E Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['Db Minor Triad (i)', 'Gb Minor Triad (iv)', 'Ab Major Triad (V)'],
    relatedArpeggios: ['Db Minor Arpeggio', 'E Augmented Arpeggio'],
    playNotes: ['Db4', 'Eb4', 'E4', 'Gb4', 'Ab4', 'A4', 'C5', 'Db5'],
    enharmonicEquivalent: 'C# Harmonic Minor',
  },
  'D Harmonic Minor': {
    name: 'D Harmonic Minor',
    keySignature: '1 Flat (C♯ raised)',
    notes: ['D', 'E', 'F', 'G', 'A', 'A#', 'C#'],
    relativeMinor: 'F Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['D Minor Triad (i)', 'G Minor Triad (iv)', 'A Major Triad (V)'],
    relatedArpeggios: ['D Minor Arpeggio', 'F Augmented Arpeggio'],
    playNotes: ['D4', 'E4', 'F4', 'G4', 'A4', 'Bb4', 'C#5', 'D5'],
  },
  'D# Harmonic Minor': {
    name: 'D# Harmonic Minor',
    keySignature: '6 Sharps (C𝄪 raised)',
    notes: ['D#', 'F', 'F#', 'G#', 'A#', 'B', 'D'],
    relativeMinor: 'F# Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['D# Minor Triad (i)', 'G# Minor Triad (iv)', 'A# Major Triad (V)'],
    relatedArpeggios: ['D# Minor Arpeggio', 'F# Augmented Arpeggio'],
    playNotes: ['D#4', 'F4', 'F#4', 'G#4', 'A#4', 'B4', 'D5', 'D#5'],
    enharmonicEquivalent: 'Eb Harmonic Minor',
  },
  'Eb Harmonic Minor': {
    name: 'Eb Harmonic Minor',
    keySignature: '6 Flats (D♮ raised)',
    notes: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'B', 'D'],
    relativeMinor: 'Gb Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Eb Minor Triad (i)', 'Ab Minor Triad (iv)', 'Bb Major Triad (V)'],
    relatedArpeggios: ['Eb Minor Arpeggio', 'Gb Augmented Arpeggio'],
    playNotes: ['Eb4', 'F4', 'Gb4', 'Ab4', 'Bb4', 'B4', 'D5', 'Eb5'],
    enharmonicEquivalent: 'D# Harmonic Minor',
  },
  'E Harmonic Minor': {
    name: 'E Harmonic Minor',
    keySignature: '1 Sharp (D♯ raised)',
    notes: ['E', 'F#', 'G', 'A', 'B', 'C', 'D#'],
    relativeMinor: 'G Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['E Minor Triad (i)', 'A Minor Triad (iv)', 'B Major Triad (V)'],
    relatedArpeggios: ['E Minor Arpeggio', 'G Augmented Arpeggio'],
    playNotes: ['E4', 'F#4', 'G4', 'A4', 'B4', 'C5', 'D#5', 'E5'],
  },
  'F Harmonic Minor': {
    name: 'F Harmonic Minor',
    keySignature: '4 Flats (E♮ raised)',
    notes: ['F', 'G', 'G#', 'A#', 'C', 'C#', 'E'],
    relativeMinor: 'Ab Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-4-1-2-3-4',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['F Minor Triad (i)', 'Bb Minor Triad (iv)', 'C Major Triad (V)'],
    relatedArpeggios: ['F Minor Arpeggio', 'Ab Augmented Arpeggio'],
    playNotes: ['F4', 'G4', 'Ab4', 'Bb4', 'C5', 'Db5', 'E5', 'F5'],
  },
  'F# Harmonic Minor': {
    name: 'F# Harmonic Minor',
    keySignature: '3 Sharps (E♯ raised)',
    notes: ['F#', 'G#', 'A', 'B', 'C#', 'D', 'F'],
    relativeMinor: 'A Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Advanced',
    relatedChords: ['F# Minor Triad (i)', 'B Minor Triad (iv)', 'C# Major Triad (V)'],
    relatedArpeggios: ['F# Minor Arpeggio', 'A Augmented Arpeggio'],
    playNotes: ['F#4', 'G#4', 'A4', 'B4', 'C#5', 'D5', 'F5', 'F#5'],
    enharmonicEquivalent: 'Gb Harmonic Minor',
  },
  'Gb Harmonic Minor': {
    name: 'Gb Harmonic Minor',
    keySignature: '9 Flats (F♮ raised)',
    notes: ['Gb', 'Ab', 'A', 'B', 'Db', 'D', 'F'],
    relativeMinor: 'A Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Advanced',
    relatedChords: ['Gb Minor Triad (i)', 'Cb Minor Triad (iv)', 'Db Major Triad (V)'],
    relatedArpeggios: ['Gb Minor Arpeggio', 'A Augmented Arpeggio'],
    playNotes: ['Gb4', 'Ab4', 'A4', 'B4', 'Db5', 'D5', 'F5', 'Gb5'],
    enharmonicEquivalent: 'F# Harmonic Minor',
  },
  'G Harmonic Minor': {
    name: 'G Harmonic Minor',
    keySignature: '2 Flats (F♯ raised)',
    notes: ['G', 'A', 'A#', 'C', 'D', 'D#', 'F#'],
    relativeMinor: 'Bb Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['G Minor Triad (i)', 'C Minor Triad (iv)', 'D Major Triad (V)'],
    relatedArpeggios: ['G Minor Arpeggio', 'Bb Augmented Arpeggio'],
    playNotes: ['G4', 'A4', 'Bb4', 'C5', 'D5', 'Eb5', 'F#5', 'G5'],
  },
  'G# Harmonic Minor': {
    name: 'G# Harmonic Minor',
    keySignature: '5 Sharps (F## raised)',
    notes: ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'G'],
    relativeMinor: 'B Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['G# Minor Triad (i)', 'C# Minor Triad (iv)', 'D# Major Triad (V)'],
    relatedArpeggios: ['G# Minor Arpeggio', 'B Augmented Arpeggio'],
    playNotes: ['G#4', 'A#4', 'B4', 'C#5', 'D#5', 'E5', 'G5', 'G#5'],
    enharmonicEquivalent: 'Ab Harmonic Minor',
  },
  'Ab Harmonic Minor': {
    name: 'Ab Harmonic Minor',
    keySignature: '7 Flats (G♮ raised)',
    notes: ['Ab', 'Bb', 'B', 'Db', 'Eb', 'E', 'G'],
    relativeMinor: 'B Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Ab Minor Triad (i)', 'Db Minor Triad (iv)', 'Eb Major Triad (V)'],
    relatedArpeggios: ['Ab Minor Arpeggio', 'B Augmented Arpeggio'],
    playNotes: ['Ab4', 'Bb4', 'B4', 'Db5', 'Eb5', 'E5', 'G5', 'Ab5'],
    enharmonicEquivalent: 'G# Harmonic Minor',
  },
  'A Harmonic Minor': {
    name: 'A Harmonic Minor',
    keySignature: '0 Sharps/Flats (G♯ raised)',
    notes: ['A', 'B', 'C', 'D', 'E', 'F', 'G#'],
    relativeMinor: 'C Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['A Minor Triad (i)', 'D Minor Triad (iv)', 'E Major Triad (V)'],
    relatedArpeggios: ['A Minor Arpeggio', 'C Augmented Arpeggio'],
    playNotes: ['A4', 'B4', 'C5', 'D5', 'E5', 'F5', 'G#5', 'A5'],
  },
  'A# Harmonic Minor': {
    name: 'A# Harmonic Minor',
    keySignature: '7 Sharps (G𝄪 raised)',
    notes: ['A#', 'C', 'C#', 'D#', 'F', 'F#', 'A'],
    relativeMinor: 'C# Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['A# Minor Triad (i)', 'D# Minor Triad (iv)', 'E# Major Triad (V)'],
    relatedArpeggios: ['A# Minor Arpeggio', 'C# Augmented Arpeggio'],
    playNotes: ['A#4', 'C5', 'C#5', 'D#5', 'F5', 'F#5', 'A5', 'A#5'],
    enharmonicEquivalent: 'Bb Harmonic Minor',
  },
  'Bb Harmonic Minor': {
    name: 'Bb Harmonic Minor',
    keySignature: '5 Flats (A♮ raised)',
    notes: ['Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'A'],
    relativeMinor: 'Db Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Bb Minor Triad (i)', 'Eb Minor Triad (iv)', 'F Major Triad (V)'],
    relatedArpeggios: ['Bb Minor Arpeggio', 'Db Augmented Arpeggio'],
    playNotes: ['Bb4', 'C5', 'Db5', 'Eb5', 'F5', 'Gb5', 'A5', 'Bb5'],
    enharmonicEquivalent: 'A# Harmonic Minor',
  },
  'B Harmonic Minor': {
    name: 'B Harmonic Minor',
    keySignature: '2 Sharps (A♯ raised)',
    notes: ['B', 'C#', 'D', 'E', 'F#', 'G', 'A#'],
    relativeMinor: 'D Major (Relative Major)',
    formula: 'W-H-W-W-H-A2-H',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Intermediate',
    relatedChords: ['B Minor Triad (i)', 'E Minor Triad (iv)', 'F# Major Triad (V)'],
    relatedArpeggios: ['B Minor Arpeggio', 'D Augmented Arpeggio'],
    playNotes: ['B4', 'C#5', 'D5', 'E5', 'F#5', 'G5', 'A#5', 'B5'],
  },

  // --- MELODIC MINOR SCALES (12 Keys + 5 Enharmonics, Ascending/Descending) ---
  'C Melodic Minor': {
    name: 'C Melodic Minor',
    keySignature: '3 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['C', 'D', 'D#', 'F', 'G', 'A', 'B', 'C', 'A#', 'G#', 'G', 'F', 'D#', 'D', 'C'],
    relativeMinor: 'Eb Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['C Minor Triad (i)', 'F Major Triad (IV)', 'G Major Triad (V)'],
    relatedArpeggios: ['C Minor Arpeggio', 'Eb Major 7th'],
    playNotes: ['C4', 'D4', 'D#4', 'F4', 'G4', 'A4', 'B4', 'C5', 'A#4', 'G#4', 'G4', 'F4', 'D#4', 'D4', 'C4'],
  },
  'C# Melodic Minor': {
    name: 'C# Melodic Minor',
    keySignature: '4 Sharps (ascending raised 6th/7th, natural minor descending)',
    notes: ['C#', 'D#', 'E', 'F#', 'G#', 'A#', 'C', 'C#', 'B', 'A', 'G#', 'F#', 'E', 'D#', 'C#'],
    relativeMinor: 'E Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['C# Minor Triad (i)', 'F# Major Triad (IV)', 'G# Major Triad (V)'],
    relatedArpeggios: ['C# Minor Arpeggio', 'E Major 7th'],
    playNotes: ['C#4', 'D#4', 'E4', 'F#4', 'G#4', 'A#4', 'C5', 'C#5', 'B4', 'A4', 'G#4', 'F#4', 'E4', 'D#4', 'C#4'],
    enharmonicEquivalent: 'Db Melodic Minor',
  },
  'Db Melodic Minor': {
    name: 'Db Melodic Minor',
    keySignature: '8 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['Db', 'Eb', 'E', 'Gb', 'Ab', 'Bb', 'C', 'Db', 'B', 'A', 'Ab', 'Gb', 'E', 'Eb', 'Db'],
    relativeMinor: 'E Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['Db Minor Triad (i)', 'Gb Major Triad (IV)', 'Ab Major Triad (V)'],
    relatedArpeggios: ['Db Minor Arpeggio', 'E Major 7th'],
    playNotes: ['Db4', 'Eb4', 'E4', 'Gb4', 'Ab4', 'Bb4', 'C5', 'Db5', 'B4', 'A4', 'Ab4', 'Gb4', 'E4', 'Eb4', 'Db4'],
    enharmonicEquivalent: 'C# Melodic Minor',
  },
  'D Melodic Minor': {
    name: 'D Melodic Minor',
    keySignature: '1 Flat (ascending raised 6th/7th, natural minor descending)',
    notes: ['D', 'E', 'F', 'G', 'A', 'B', 'C#', 'D', 'C', 'A#', 'A', 'G', 'F', 'E', 'D'],
    relativeMinor: 'F Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['D Minor Triad (i)', 'G Major Triad (IV)', 'A Major Triad (V)'],
    relatedArpeggios: ['D Minor Arpeggio', 'F Major 7th'],
    playNotes: ['D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C#5', 'D5', 'C5', 'A#4', 'A4', 'G4', 'F4', 'E4', 'D4'],
  },
  'D# Melodic Minor': {
    name: 'D# Melodic Minor',
    keySignature: '6 Sharps (ascending raised 6th/7th, natural minor descending)',
    notes: ['D#', 'F', 'F#', 'G#', 'A#', 'C', 'D', 'D#', 'C#', 'B', 'A#', 'G#', 'F#', 'F', 'D#'],
    relativeMinor: 'F# Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['D# Minor Triad (i)', 'G# Major Triad (IV)', 'A# Major Triad (V)'],
    relatedArpeggios: ['D# Minor Arpeggio', 'F# Major 7th'],
    playNotes: ['D#4', 'F4', 'F#4', 'G#4', 'A#4', 'C5', 'D5', 'D#5', 'C#5', 'B4', 'A#4', 'G#4', 'F#4', 'F4', 'D#4'],
    enharmonicEquivalent: 'Eb Melodic Minor',
  },
  'Eb Melodic Minor': {
    name: 'Eb Melodic Minor',
    keySignature: '6 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['Eb', 'F', 'Gb', 'Ab', 'Bb', 'C', 'D', 'Eb', 'Db', 'B', 'Bb', 'Ab', 'Gb', 'F', 'Eb'],
    relativeMinor: 'Gb Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Eb Minor Triad (i)', 'Ab Major Triad (IV)', 'Bb Major Triad (V)'],
    relatedArpeggios: ['Eb Minor Arpeggio', 'Gb Major 7th'],
    playNotes: ['Eb4', 'F4', 'Gb4', 'Ab4', 'Bb4', 'C5', 'D5', 'Eb5', 'Db5', 'B4', 'Bb4', 'Ab4', 'Gb4', 'F4', 'Eb4'],
    enharmonicEquivalent: 'D# Melodic Minor',
  },
  'E Melodic Minor': {
    name: 'E Melodic Minor',
    keySignature: '1 Sharp (ascending raised 6th/7th, natural minor descending)',
    notes: ['E', 'F#', 'G', 'A', 'B', 'C#', 'D#', 'E', 'D', 'C', 'B', 'A', 'G', 'F#', 'E'],
    relativeMinor: 'G Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['E Minor Triad (i)', 'A Major Triad (IV)', 'B Major Triad (V)'],
    relatedArpeggios: ['E Minor Arpeggio', 'G Major 7th'],
    playNotes: ['E4', 'F#4', 'G4', 'A4', 'B4', 'C#5', 'D#5', 'E5', 'D5', 'C5', 'B4', 'A4', 'G4', 'F#4', 'E4'],
  },
  'F Melodic Minor': {
    name: 'F Melodic Minor',
    keySignature: '4 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['F', 'G', 'G#', 'A#', 'C', 'D', 'E', 'F', 'D#', 'C#', 'C', 'A#', 'G#', 'G', 'F'],
    relativeMinor: 'Ab Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-4-1-2-3-4',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['F Minor Triad (i)', 'Bb Major Triad (IV)', 'C Major Triad (V)'],
    relatedArpeggios: ['F Minor Arpeggio', 'Ab Major 7th'],
    playNotes: ['F4', 'G4', 'G#4', 'A#4', 'C5', 'D5', 'E5', 'F5', 'D#5', 'C#5', 'C5', 'A#4', 'G#4', 'G4', 'F4'],
  },
  'F# Melodic Minor': {
    name: 'F# Melodic Minor',
    keySignature: '3 Sharps (ascending raised 6th/7th, natural minor descending)',
    notes: ['F#', 'G#', 'A', 'B', 'C#', 'D#', 'F', 'F#', 'E', 'D', 'C#', 'B', 'A', 'G#', 'F#'],
    relativeMinor: 'A Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Advanced',
    relatedChords: ['F# Minor Triad (i)', 'B Major Triad (IV)', 'C# Major Triad (V)'],
    relatedArpeggios: ['F# Minor Arpeggio', 'A Major 7th'],
    playNotes: ['F#4', 'G#4', 'A4', 'B4', 'C#5', 'D#5', 'F5', 'F#5', 'E5', 'D5', 'C#5', 'B4', 'A4', 'G#4', 'F#4'],
    enharmonicEquivalent: 'Gb Melodic Minor',
  },
  'Gb Melodic Minor': {
    name: 'Gb Melodic Minor',
    keySignature: '9 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['Gb', 'Ab', 'A', 'B', 'Db', 'Eb', 'F', 'Gb', 'E', 'D', 'Db', 'B', 'A', 'Ab', 'Gb'],
    relativeMinor: 'A Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-3-1-2-3-4-1-2',
    leftHandFingering: '4-3-2-1-3-2-1-4',
    difficulty: 'Advanced',
    relatedChords: ['Gb Minor Triad (i)', 'Cb Major Triad (IV)', 'Db Major Triad (V)'],
    relatedArpeggios: ['Gb Minor Arpeggio', 'A Major 7th'],
    playNotes: ['Gb4', 'Ab4', 'A4', 'B4', 'Db5', 'Eb5', 'F5', 'Gb5', 'E5', 'D5', 'Db5', 'B4', 'A4', 'Ab4', 'Gb4'],
    enharmonicEquivalent: 'F# Melodic Minor',
  },
  'G Melodic Minor': {
    name: 'G Melodic Minor',
    keySignature: '2 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['G', 'A', 'A#', 'C', 'D', 'E', 'F#', 'G', 'F', 'D#', 'D', 'C', 'A#', 'A', 'G'],
    relativeMinor: 'Bb Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['G Minor Triad (i)', 'C Major Triad (IV)', 'D Major Triad (V)'],
    relatedArpeggios: ['G Minor Arpeggio', 'Bb Major 7th'],
    playNotes: ['G4', 'A4', 'A#4', 'C5', 'D5', 'E5', 'F#5', 'G5', 'F5', 'D#5', 'D5', 'C5', 'A#4', 'A4', 'G4'],
  },
  'G# Melodic Minor': {
    name: 'G# Melodic Minor',
    keySignature: '5 Sharps (ascending raised 6th/7th, natural minor descending)',
    notes: ['G#', 'A#', 'B', 'C#', 'D#', 'F', 'G', 'G#', 'F#', 'E', 'D#', 'C#', 'B', 'A#', 'G#'],
    relativeMinor: 'B Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['G# Minor Triad (i)', 'C# Major Triad (IV)', 'D# Major Triad (V)'],
    relatedArpeggios: ['G# Minor Arpeggio', 'B Major 7th'],
    playNotes: ['G#4', 'A#4', 'B4', 'C#5', 'D#5', 'F5', 'G5', 'G#5', 'F#5', 'E5', 'D#5', 'C#5', 'B4', 'A#4', 'G#4'],
    enharmonicEquivalent: 'Ab Melodic Minor',
  },
  'Ab Melodic Minor': {
    name: 'Ab Melodic Minor',
    keySignature: '7 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['Ab', 'Bb', 'B', 'Db', 'Eb', 'F', 'G', 'Ab', 'Gb', 'E', 'Eb', 'Db', 'B', 'Bb', 'Ab'],
    relativeMinor: 'B Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '3-4-1-2-3-1-2-3',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Ab Minor Triad (i)', 'Db Major Triad (IV)', 'Eb Major Triad (V)'],
    relatedArpeggios: ['Ab Minor Arpeggio', 'B Major 7th'],
    playNotes: ['Ab4', 'Bb4', 'B4', 'Db5', 'Eb5', 'F5', 'G5', 'Ab5', 'Gb5', 'E5', 'Eb5', 'Db5', 'B4', 'Bb4', 'Ab4'],
    enharmonicEquivalent: 'G# Melodic Minor',
  },
  'A Melodic Minor': {
    name: 'A Melodic Minor',
    keySignature: '0 Sharps/Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['A', 'B', 'C', 'D', 'E', 'F#', 'G#', 'A', 'G', 'F', 'E', 'D', 'C', 'B', 'A'],
    relativeMinor: 'C Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['A Minor Triad (i)', 'D Major Triad (IV)', 'E Major Triad (V)'],
    relatedArpeggios: ['A Minor Arpeggio', 'C Major 7th'],
    playNotes: ['A4', 'B4', 'C5', 'D5', 'E5', 'F#5', 'G#5', 'A5', 'G5', 'F5', 'E5', 'D5', 'C5', 'B4', 'A4'],
  },
  'A# Melodic Minor': {
    name: 'A# Melodic Minor',
    keySignature: '7 Sharps (ascending raised 6th/7th, natural minor descending)',
    notes: ['A#', 'C', 'C#', 'D#', 'F', 'G', 'A', 'A#', 'G#', 'F#', 'F', 'D#', 'C#', 'C', 'A#'],
    relativeMinor: 'C# Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['A# Minor Triad (i)', 'D# Major Triad (IV)', 'E# Major Triad (V)'],
    relatedArpeggios: ['A# Minor Arpeggio', 'C# Major 7th'],
    playNotes: ['A#4', 'C5', 'C#5', 'D#5', 'F5', 'G5', 'A5', 'A#5', 'G#5', 'F#5', 'F5', 'D#5', 'C#5', 'C5', 'A#4'],
    enharmonicEquivalent: 'Bb Melodic Minor',
  },
  'Bb Melodic Minor': {
    name: 'Bb Melodic Minor',
    keySignature: '5 Flats (ascending raised 6th/7th, natural minor descending)',
    notes: ['Bb', 'C', 'Db', 'Eb', 'F', 'G', 'A', 'Bb', 'Ab', 'Gb', 'F', 'Eb', 'Db', 'C', 'Bb'],
    relativeMinor: 'Db Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '2-1-2-3-1-2-3-4',
    leftHandFingering: '3-2-1-4-3-2-1-3',
    difficulty: 'Advanced',
    relatedChords: ['Bb Minor Triad (i)', 'Eb Major Triad (IV)', 'F Major Triad (V)'],
    relatedArpeggios: ['Bb Minor Arpeggio', 'Db Major 7th'],
    playNotes: ['Bb4', 'C5', 'Db5', 'Eb5', 'F5', 'G5', 'A5', 'Bb5', 'Ab5', 'Gb5', 'F5', 'Eb5', 'Db5', 'C5', 'Bb4'],
    enharmonicEquivalent: 'A# Melodic Minor',
  },
  'B Melodic Minor': {
    name: 'B Melodic Minor',
    keySignature: '2 Sharps (ascending raised 6th/7th, natural minor descending)',
    notes: ['B', 'C#', 'D', 'E', 'F#', 'G#', 'A#', 'B', 'A', 'G', 'F#', 'E', 'D', 'C#', 'B'],
    relativeMinor: 'D Major (Relative Major)',
    formula: 'W-H-W-W-W-W-H / W-H-W-W-H-W-W',
    degrees: ['1', '2', '3', '4', '5', '6', '7'],
    degreeNames: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant', 'Dominant', 'Submediant', 'Leading Tone'],
    rightHandFingering: '1-2-3-1-2-3-4-5',
    leftHandFingering: '5-4-3-2-1-3-2-1',
    difficulty: 'Advanced',
    relatedChords: ['B Minor Triad (i)', 'E Major Triad (IV)', 'F# Major Triad (V)'],
    relatedArpeggios: ['B Minor Arpeggio', 'D Major 7th'],
    playNotes: ['B4', 'C#5', 'D5', 'E5', 'F#5', 'G#5', 'A#5', 'B5', 'A5', 'G5', 'F#5', 'E5', 'D5', 'C#5', 'B4'],
  },
};
